# Generated by Django 5.2.5 on 2025-09-04 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_contenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dateFabric',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
