# Generated by Django 5.2.5 on 2025-09-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0004_produit_datefabric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idStat', models.AutoField(primary_key=True, serialize=False)),
                ('libelleStat', models.CharField(max_length=100)),
            ],
        ),
    ]
