# Generated by Django 5.2.5 on 2025-09-08 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_produit_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='dateFabric',
            new_name='dateFabProd',
        ),
        migrations.RenameField(
            model_name='statut',
            old_name='idStat',
            new_name='idStatus',
        ),
        migrations.RenameField(
            model_name='statut',
            old_name='libelleStat',
            new_name='libelleStatus',
        ),
        migrations.RemoveField(
            model_name='contenir',
            name='qte',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='statut',
        ),
        migrations.AddField(
            model_name='produit',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_status', to='monApp.statut'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_categorie', to='monApp.categorie'),
        ),
        migrations.AddField(
            model_name='contenir',
            name='Qte',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
